### ISSUE TITLE
build-prod

### ISSUE THREAD

**Issue by appinteractive** [demokratie-live/desktop#10]
Sollten wir nicht den Prod build nutzen wir in der Dokumentation erwähnt? `yarn build-prod`

**Comment by ManAnRuck** [comment]
Guter Punkt. Das hatte ich noch nicht gesehen. Sollten wir bei Gelegenheit mal prüfen und wenn es sich lohnt umsetzen.

**Comment by ManAnRuck** [comment]
Hab's grad einfach mal lokal ausgeführt und bekomme folgenden Fehler:
```
Error: Image Optimization using Next.js' default loader is not compatible with `next export`.
  Possible solutions:
    - Use `next start` to run a server, which includes the Image Optimization API.
    - Use any provider which supports Image Optimization (like Vercel).
    - Configure a third-party loader in `next.config.js`.
    - Use the `loader` prop for `next/image`.
  Read more: https://nextjs.org/docs/messages/export-image-api
    at PATH/democracy/repos/democracy-desktop/node_modules/next/dist/export/index.js:157:23
    at async Span.traceAsyncFn (PATH/democracy/repos/democracy-desktop/node_modules/next/dist/trace/trace.js:79:20)
 ```
 
 hab mich jedoch noch nicht damit beschäftigt.

**Comment by appinteractive** [comment]
Um ehrlich zu sein, finde ich dieses ganze Next Image Gedöns unfassbar kompliziert und verwirrend. Die Dokumentation ist auch recht dünn. Müsste ich mich auch (zum fünften Mal) versuchen einzulesen.

Hätte gehofft das du da mehr weißt als ich Next noob. Hab aber das Gefühl das diese Komponente kaum jemand nutzt, der static baut. Wenn du in der Doku danach suchst, in Kombination mit Export findest du nur das JS `export` Keyword, irgendwie etwas unglücklich benahmt.

**Comment by appinteractive** [comment]
Die Image-Komponente optimiert die Bilder scheinbar gar nicht, sondern baut nur stumpfe URLs für CDNs oder Image Services. Nützt einem ohne solch einen Service dann natürlich nichts, etwas sehr unglücklich wie ich finde.

**Comment by appinteractive** [comment]
es scheint folgende Lösung zu geben: https://github.com/Niels-IO/next-image-export-optimizer. 

Aus folgenem Post: https://stackoverflow.com/questions/75637767/next-js-ssg-image-optimization-at-build-time


müsste ich in ruhe mal dran

**Comment by ManAnRuck** [comment]
Schau ich mir bei Gelegenheit auch nochmal an :)
